const wh = '#fcfcfc'
const no = ''

export const spawn = {
	t1: [
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, wh, wh, wh, wh, wh, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
	],
	t2: [
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, wh, wh, wh, wh, wh, wh, wh, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
	],
	t3: [
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, wh, wh, wh, wh, wh, wh, wh, no, no, no, no],
		[no, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, no],
		[no, no, no, no, wh, wh, wh, wh, wh, wh, wh, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, no, no, no, no, no, no, no, no],
	],
	t4: [
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, no, wh, wh, wh, wh, wh, no, no, no, no, no],
		[no, no, no, wh, wh, wh, wh, wh, wh, wh, wh, wh, no, no, no],
		[wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh],
		[no, no, no, wh, wh, wh, wh, wh, wh, wh, wh, wh, no, no, no],
		[no, no, no, no, no, wh, wh, wh, wh, wh, no, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, no, no, wh, wh, wh, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
		[no, no, no, no, no, no, no, wh, no, no, no, no, no, no, no],
	],
}
