export * from './bang.instances'
export * from './bonus.instances'
export * from './bullet.instances'
export * from './coordinates.instances'
export * from './game-object.instances'
export * from './game.instances'
export * from './player.instances'
export * from './tank.instances'
